export default function Detail() {
  return <h1>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Minus nam unde, ullam ipsam quod aliquid laborum vero quos dignissimos deserunt maiores ad laboriosam! Veniam temporibus labore eos, maiores aliquid deserunt.
  Quia velit rem iure quaerat vitae quo expedita, suscipit qui id totam culpa consectetur. Magnam similique numquam expedita qui fugit laboriosam, rem, quaerat libero natus nihil corrupti. Vero, molestias natus!
  Labore quisquam autem inventore, dolor a officiis saepe necessitatibus quidem, quod ut voluptatibus, porro voluptatem odio doloremque accusamus eum at nemo. Quod id aut laboriosam repellendus amet delectus hic numquam.
  Voluptate suscipit eligendi aliquid. Nulla mollitia optio iure, quisquam adipisci obcaecati. Est nihil dolores sequi laborum et unde rem, dolorem quas nobis ipsam explicabo optio doloremque eos magnam nisi quae!
  Nemo officia saepe provident ad, obcaecati tempora quod eius cum hic dolores, quo dicta repellendus nam vel eveniet sint ut optio! Veniam, excepturi placeat aspernatur ut nobis accusamus asperiores optio?
  In sequi sit minus. Quam consequuntur quos, odio impedit, sapiente recusandae doloremque ea dolorem expedita consectetur natus quo ipsum! Neque adipisci at magni corrupti, quia consequuntur provident dolore iure voluptatem?
  Officia commodi velit, dolorum ducimus perspiciatis accusantium deleniti iure soluta et adipisci maiores porro reiciendis saepe non id incidunt illum, enim neque veniam pariatur dolores ad unde rerum. Impedit, numquam?
  Fugit sunt architecto fugiat nesciunt minima odit. Fugiat architecto eum amet alias incidunt quaerat error facilis corporis atque neque enim laborum quisquam, expedita magni dolores consequuntur ab quam, impedit repellat.
  Esse earum facilis laborum quam dolorem fugit fuga amet placeat excepturi aliquid assumenda maiores consequuntur, commodi cum officia consectetur non delectus. Expedita, ducimus quas aliquam adipisci molestiae est laboriosam nihil.
  Qui animi repellat, assumenda laborum ipsum sint, quae ut id culpa ullam ad obcaecati! Modi, eos at quia consectetur, saepe quibusdam nemo, maxime quo adipisci totam iusto a deleniti corrupti?
  Consectetur doloribus sit nisi nemo ullam suscipit qui repellendus soluta at, iste consequatur magnam fugit illo. Soluta, aperiam ullam? Doloremque quos ea inventore. Assumenda quis, adipisci aliquam necessitatibus maxime fuga!
  Iste totam dignissimos culpa quasi! Modi asperiores magni impedit possimus voluptatum. Assumenda facere sunt itaque alias tempora cupiditate possimus modi earum in vitae iste iure et, debitis suscipit officia harum!
  Obcaecati, quas, hic veritatis beatae sint facilis voluptates itaque nam eos cumque quidem laboriosam delectus saepe? Similique, atque numquam quisquam omnis voluptas totam dicta sapiente corrupti fugit blanditiis sunt perferendis.
  Veniam optio inventore cum debitis deleniti fuga ea commodi, accusantium adipisci, at officia hic saepe quisquam atque aliquid. Dicta totam modi eligendi perspiciatis iusto vitae nostrum corporis autem optio voluptatem!
  Alias sed modi dignissimos at id nesciunt fuga ea dicta a aliquid. Dolor a, minima quam cupiditate assumenda odio? Totam unde qui tempore commodi dolor atque temporibus, molestias perspiciatis aperiam!
  Omnis porro quam sapiente neque recusandae provident pariatur harum rem corrupti animi ducimus repellat, magnam nemo cupiditate labore tempora in, iste deserunt consequatur ullam quidem placeat. Numquam ullam totam molestias!
  Vitae nulla, debitis dolorum quae corporis amet reprehenderit consequatur minus atque, illum culpa labore! Sequi facilis optio nostrum eos dolor corrupti unde quaerat blanditiis eveniet atque, esse, debitis consequatur veniam!
  Reiciendis voluptate in similique quas maxime architecto, dicta quo dolorum minus animi ipsa esse tenetur deleniti iusto eos, explicabo quae tempora dolores. Veniam officiis exercitationem, facere enim autem ducimus facilis?
  Sunt quos earum quas quibusdam ullam doloribus fugit quis, distinctio nisi consectetur, officiis culpa quam omnis exercitationem quasi nemo soluta incidunt qui enim, obcaecati illo magnam! Porro dolor quaerat voluptate.
  Distinctio veniam enim itaque ea impedit autem quaerat vitae quos nemo rerum! Similique exercitationem et at, porro atque ab minus dolor nihil necessitatibus sapiente temporibus esse laudantium, adipisci quasi libero!
  Quam voluptates asperiores aut id iste possimus eveniet aspernatur libero modi. Reiciendis, voluptates! Inventore placeat nemo a molestias laboriosam velit. Veniam nesciunt maiores libero quod corporis quisquam labore voluptates quibusdam!
  Voluptatum suscipit sapiente iure, recusandae dicta quia itaque expedita molestias, sit distinctio doloremque, ipsa minima nisi ratione consequuntur rerum laboriosam neque quisquam pariatur hic architecto. Nobis ut officiis alias quas!
  Aliquam corrupti repellendus aperiam ad quae commodi enim quam et, eos, eum natus ipsa voluptatibus tempora consectetur tenetur. Magni velit quidem maxime nobis minus harum eveniet quod itaque. Harum, quod!
  Consequuntur fugiat voluptas quia provident enim, atque repellendus reprehenderit molestiae dolore ipsa. Modi, quasi temporibus nulla deleniti assumenda culpa natus praesentium quaerat omnis, reprehenderit quia est? Earum vitae nisi voluptate!
  Doloremque, corrupti. Consequatur qui illo officiis reiciendis iure corporis, vitae laudantium, tenetur beatae sunt id nihil! Quidem expedita doloremque ut inventore quae. Explicabo veniam temporibus error ullam laboriosam iure culpa.
  Voluptatem doloremque possimus quam debitis accusamus quidem! Asperiores et vitae magni perferendis ratione hic nostrum. Unde nihil, consequatur soluta laudantium voluptatibus aliquid error quos porro officiis fuga dignissimos, at sapiente.
  Neque id modi fugiat quo amet fuga dolorem in expedita earum veritatis ducimus iusto nostrum nobis quidem repellat dolore exercitationem, ratione laborum qui vitae? Repudiandae aliquam numquam repellendus hic nemo?
  Animi quidem eveniet tenetur numquam quisquam repellendus explicabo quaerat, mollitia officiis quia iure magnam similique quasi reiciendis voluptatem voluptates? Obcaecati explicabo eos ipsam voluptate labore illum veniam. Vitae, sequi obcaecati.
  Accusantium distinctio omnis saepe corrupti nihil eaque nobis molestiae quod libero eum aperiam, fugiat, iusto illo nam nemo dignissimos deleniti aliquid deserunt ratione dicta expedita culpa architecto dolor ipsa! Quisquam.
  Ratione at rem nam? Veritatis qui dolorem ipsam quae ad porro dolore quibusdam at facilis officia magni assumenda quasi eligendi, iusto, cum consequatur accusamus numquam. Error minima dolorum dolores expedita?</h1>;
}
